### ISSUE TITLE
How do I search all public repositories at one?

### ISSUE THREAD

**Issue by Zir0-93** [codota/codota-sdk-samples#1]
Hi there, The Codota SDK has been great at finding code snippets from a single public repository. Is there a way to search more than one public repository at a time via multiple code packs? Or even better yet, all public open source repositories in a single query? Thanks in advance.

**Comment by drorweiss** [comment]
Hi there!
Try using CodotaSearchClient.search() to search public repositories.
It's a wrapper around our search API endpoint. Try for example using it for searching "android.media.MediaRecorder" - it should return the same data as this api call - http://www.codota.com/api/search?q=android.media.MediaRecorder.

We currently cover Java and Android classes, and a few select libraries - expanding very soon.
I hope to add an example soon to this repo.
